steps:
# 1. Construir la imagen de Docker del Frontend
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
    - 'build'
    - '-t'
    - 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/personalfinance.api.frontend/personalfinance-api-frontend:$COMMIT_SHA'
    - '--build-arg'
    # 💡 Importante: Aquí pasamos la URL del backend a la variable VITE_API_URL
    - 'VITE_API_URL=https://personalfinance-api-backend-246552849554.europe-southwest1.run.app'
    - '.'

# 2. Subir la imagen al Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
    - 'push'
    - 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/personalfinance.api.frontend/personalfinance-api-frontend:$COMMIT_SHA'

# 3. Desplegar la imagen en Cloud Run (Frontend)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Deploy
  args:
    - 'run'
    - 'deploy'
    - 'personalfinance-api-frontend'
    - '--image'
    - 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/personalfinance.api.frontend/personalfinance-api-frontend:$COMMIT_SHA'
    - '--region'
    - 'europe-southwest1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8080' # 💡 Cloud Run espera que el contenedor escuche en 8080
    - '--quiet'
timeout: '1600s'

# Guardamos la imagen en Artifact Registry
images:
- 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/personalfinance.api.frontend/personalfinance-api-frontend:$COMMIT_SHA'