steps:
# 1. Construir la imagen de Docker del Frontend (IGNORANDO CACHÉ)
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
    - 'build'
    - '-t'
    - 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/personalfinance.api.frontend/personalfinance-api-frontend:$COMMIT_SHA'
    - '--build-arg'
    # 💡 URL del Backend
    - 'VITE_API_URL=https://personalfinanceapifrontend-production.up.railway.app'
    - '--no-cache' # <--- OBLIGA A RECONSTRUIR TODO
    - '.'

# 2. Subir la imagen al Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
    - 'push'
    - 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/personalfinance.api.frontend/personalfinance-api-frontend:$COMMIT_SHA'

# 3. Desplegar la imagen en Cloud Run (Frontend)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Deploy
  args:
    - 'run'
    - 'deploy'
    - 'personalfinance-api-frontend'
    - '--image'
    # Usamos el hash del commit para asegurar que Cloud Run despliega la nueva imagen
    - 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/personalfinance.api.frontend/personalfinance-api-frontend:$COMMIT_SHA'
    - '--region'
    - 'europe-southwest1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'
    - '--quiet'
timeout: '1600s'

# Guardamos la imagen en Artifact Registry
images:
- 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/personalfinance.api.frontend/personalfinance-api-frontend:$COMMIT_SHA'

# 🚨 SOLUCIÓN AL ERROR DEL ACTIVADOR: Indica dónde almacenar los logs.
options:
  logging: CLOUD_LOGGING_ONLY